version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u252-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew gulpTests
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
